set-option -g mouse on
set-option -s escape-time 10

set-option -g status-left ''
set-option -g status-right ''
set-option -g status-style 'fg=green'

set-option -g window-status-separator '|'
set-option -g window-status-current-style 'fg=green bg=colour237'
set-option -g window-status-current-format ' [#I] #[fg=white]#W '

set-option -g window-status-style 'fg=green bg=black'
set-option -g window-status-format ' [#I] #[fg=white]#W '

set-option -g window-status-bell-style 'fg=green bg=white bold'
